name: Bug report
description: Create a bug report to help us address errors in the repository
title: "[BUG] <bug description>"
labels: [bug]
body:
  - type: input
    id: bugdescription
    attributes:
      label: Description of the bug
    validations:
      required: true
  - type: input
    id: stack
    attributes:
      label: Project stack or language (e.g. front-end)
    validations:
      required: true
  - type: input
    id: workingenvironment
    attributes:
      label: Working Environment (e.g. operating system, browser, device)
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Please add screenshots (if applicable)
    validations:
      required: false
  - type: input
    id: context
    attributes:
      label: Add any other context about the problem here
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        You can also join the Discord community [here](http://discord.eddiehub.org)
        Feel free to check out other cool repositories of the EddieHub Community [here](https://github.com/EddieHubCommunity)
