name: GitHub Profile Review
description: Please review my GitHub profile on a live stream
title: "[REVIEW] <your-username>"
labels: [gh profile review, live stream review]
body:
  - type: input
    id: link
    attributes:
      label: GitHub Profile Link
      placeholder: https://github.com/<your-username>
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        You can also join the Discord community [here](http://discord.eddiehub.org)
        Feel free to check out other cool repositories of the EddieHub Community [here](https://github.com/EddieHubCommunity)
