name: Ideas
description: Have a new idea or feature request
title: "[FEATURE REQUEST] <description here>"
labels: [enhancement]
body:
  - type: input
    id: description
    attributes:
      label: Description of feature request, idea
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Add (multiple) screenshot links (if applicable)
    validations:
      required: false
  - type: input
    id: context
    attributes:
      label: Add any other context about the feature request here
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        You can also join the Discord community [here](http://discord.eddiehub.org)
        Feel free to check out other cool repositories of the EddieHub Community [here](https://github.com/EddieHubCommunity)
