name: Twitter Profile Review
description: Please review my Twitter on a livestream
title: "[REVIEW] <Twitter name here>"
labels: [twitter review, live stream review]
body:
  - type: input
    id: link
    attributes:
      label: Twitter profile link
      placeholder: https://twitter.com/<your-username>
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        You can also join our Discord community [here](http://discord.eddiehub.org)
        Feel free to check out other cool repositories of the EddieHub Community [here](https://github.com/EddieHubCommunity)
